<?xml version="1.0" encoding="utf-8"?><Database Name="WindowsFormsDemo" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=WindowsFormsDemo;Integrated Security=True" SettingsObjectName="App.LinqToSql.Properties.Settings" SettingsPropertyName="WindowsFormsDemoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categories" Member="LinqCategories">
    <Type Name="LinqCategory">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Category_Product" Member="LinqProducts" ThisKey="Id" OtherKey="CategoryId" Type="LinqProduct" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="LinqProducts">
    <Type Name="LinqProduct">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(15,2) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Category_Product" Member="LinqCategory" ThisKey="CategoryId" OtherKey="Id" Type="LinqCategory" IsForeignKey="true" />
    </Type>
  </Table>
</Database>